### ISSUE TITLE
--version flag

### ISSUE THREAD

**Issue by nguyenhung15913** [menghif/dodo-SSG#1]
![image](https://user-images.githubusercontent.com/69558780/133671912-223bb086-9a77-452e-bcdf-b7fc93ad41c7.png)

"dodo-ssg -v" does not show the name of the tool. It is supposed to provide both name of the tool and current version. To handle this issue, you can add a yargs.version() which can override the default --version.

**Comment by menghif** [comment]
fixed with commit: c25fe72bbf40b3da3e41ebab28e235abf6b495df Thank you!
