### ISSUE TITLE
Import version directly from package.json

### ISSUE THREAD

**Issue by humphd** [menghif/dodo-SSG#6]
I like how you are pulling the value for the program name from `package.json`.  You can simplify it a bit more:

```js
// current
const package = require("./package.json");
...
  .version(true, `dodo-SSG version: ${package.version}`)

// becomes
const { version } = require("./package.json");
```

**Comment by menghif** [comment]
Good point, I should have thought of it. Changed it now: a350599fe0eaf289534258aa684b62aaf573077a
